function flag = isFieldChar(c)
% Test whether characters are legal within a structure field name

flag = ((c >= 'A') && (c <= 'Z')) ...
  || ((c >= 'a') && (c <= 'z')) ...
  || ((c >= '0') && (c <= '9')) ...
  || (c == '_');
end